# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  port:
    type: int
    default: 9000
    description: HTTP port
  access-key:
    type: string
    default: 'minio'
    description: Access key
  secret-key:
    type: string
    default: ''
    description: Secret key
