# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  port:
    type: int
    default: 9000
    description: HTTP port
  console-port:
    type: int
    default: 9001
    description: HTTP port for minio console
  access-key:
    type: string
    default: 'minio'
    description: Access key
  secret-key:
    type: string
    default: ''
    description: Secret key. Must be at least 8 characters long. If not provided, a random key will be used.
  mode:
    type: string
    default: 'server'
    description: "Mode of operations. Possible values: server, gateway"
  gateway-storage-service:
    type: string
    default: ''
    description: "Storage service used by gateway to store objects. This value is required for gateway mode. Possible values: s3, azure"
  storage-service-endpoint:
    type: string
    default: ''
    description: "Service endpoint of gateway storage service. This value is optional when using S3 or Azure public API endpoints"
  ssl-ca:
    type: string
    default: ''
    description: "Base64 encoded certificate authority for untrusted certificate chains"
  ssl-cert:
    type: string
    default: ''
    description: "Base64 encoded SSL certificate."
  ssl-key:
    type: string
    default: ''
    description: "Base64 encoded SSL key."
